apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
    - name: www-html
      persistentVolumeClaim:
        claimName: pvc-1
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - name: www-html
          mountPath: /var/www/html
